# SPDX-License-Identifier: MPL-2.0

version: '3'

tasks:
  build:
    dir: apps/desktop
    cmds:
      - go tool wails3 build
  dev:
    dir: apps/desktop
    cmds:
      - go tool wails3 dev -config ./build/config.yml -port 9245
