# SPDX-License-Identifier: MPL-2.0

version: '3'

includes:
  desktop: ./apps/desktop/Taskfile.yml

tasks:
  build:
    cmds:
      - task: desktop:build
  dev:
    dir: apps/desktop
    cmds:
      - go run .
  portable:
    cmds:
      - task: desktop:package
