# SPDX-License-Identifier: MPL-2.0

version: '3'

vars:
  APP_NAME: animeportable
  BIN_DIR: bin
  TARGET_ARCH: '{{.TARGET_ARCH | default .ARCH}}'

includes:
  windows: ./build/windows/Taskfile.yml

tasks:
  build:
    cmds:
      - task: windows:build

  package:
    cmds:
      - task: windows:package

  run:
    cmds:
      - task: windows:run
