// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Anime {
    "id": string;
    "title": string;
    "nativeTitle": string;
    "description": string;

    /** Creates a new Anime instance. */
    constructor($$source: Partial<Anime> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("nativeTitle" in $$source)) {
            this["nativeTitle"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Anime instance from a string or object.
     */
    static createFrom($$source: any = {}): Anime {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Anime($$parsedSource as Partial<Anime>);
    }
}

export class Cover {
    "bytes": string;
    "mediaType": string;
    "width": number;
    "height": number;

    /** Creates a new Cover instance. */
    constructor($$source: Partial<Cover> = {}) {
        if (!("bytes" in $$source)) {
            this["bytes"] = "";
        }
        if (!("mediaType" in $$source)) {
            this["mediaType"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cover instance from a string or object.
     */
    static createFrom($$source: any = {}): Cover {
        const $$createField0_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bytes" in $$parsedSource) {
            $$parsedSource["bytes"] = $$createField0_0($$parsedSource["bytes"]);
        }
        return new Cover($$parsedSource as Partial<Cover>);
    }
}

export class Detail {
    "anime": Anime;
    "metadata"?: Metadata | null;

    /** Creates a new Detail instance. */
    constructor($$source: Partial<Detail> = {}) {
        if (!("anime" in $$source)) {
            this["anime"] = (new Anime());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Detail instance from a string or object.
     */
    static createFrom($$source: any = {}): Detail {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("anime" in $$parsedSource) {
            $$parsedSource["anime"] = $$createField0_0($$parsedSource["anime"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField1_0($$parsedSource["metadata"]);
        }
        return new Detail($$parsedSource as Partial<Detail>);
    }
}

export class Episode {
    "id": string;
    "animeId": string;
    "number": string;
    "title": string;

    /** Creates a new Episode instance. */
    constructor($$source: Partial<Episode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("animeId" in $$source)) {
            this["animeId"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Episode instance from a string or object.
     */
    static createFrom($$source: any = {}): Episode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Episode($$parsedSource as Partial<Episode>);
    }
}

export class Following {
    "animeId": string;
    "latestAvailable": string;
    "latestWatched": string;
    "hasAvailable": boolean;
    "hasWatched": boolean;
    "newEpisode": boolean;

    /** Creates a new Following instance. */
    constructor($$source: Partial<Following> = {}) {
        if (!("animeId" in $$source)) {
            this["animeId"] = "";
        }
        if (!("latestAvailable" in $$source)) {
            this["latestAvailable"] = "";
        }
        if (!("latestWatched" in $$source)) {
            this["latestWatched"] = "";
        }
        if (!("hasAvailable" in $$source)) {
            this["hasAvailable"] = false;
        }
        if (!("hasWatched" in $$source)) {
            this["hasWatched"] = false;
        }
        if (!("newEpisode" in $$source)) {
            this["newEpisode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Following instance from a string or object.
     */
    static createFrom($$source: any = {}): Following {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Following($$parsedSource as Partial<Following>);
    }
}

export class History {
    "animeId": string;
    "episodeId": string;
    "position": number;
    "duration": number;
    "completed": boolean;
    "updatedAt": string;
    "lastPlayed": string;

    /** Creates a new History instance. */
    constructor($$source: Partial<History> = {}) {
        if (!("animeId" in $$source)) {
            this["animeId"] = "";
        }
        if (!("episodeId" in $$source)) {
            this["episodeId"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("lastPlayed" in $$source)) {
            this["lastPlayed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new History instance from a string or object.
     */
    static createFrom($$source: any = {}): History {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new History($$parsedSource as Partial<History>);
    }
}

export class Metadata {
    "title": string;
    "nativeTitle": string;
    "description": string;
    "season": string;
    "year": number;
    "studio": string;
    "episodeCount": number;

    /** Creates a new Metadata instance. */
    constructor($$source: Partial<Metadata> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("nativeTitle" in $$source)) {
            this["nativeTitle"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("season" in $$source)) {
            this["season"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("studio" in $$source)) {
            this["studio"] = "";
        }
        if (!("episodeCount" in $$source)) {
            this["episodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metadata instance from a string or object.
     */
    static createFrom($$source: any = {}): Metadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metadata($$parsedSource as Partial<Metadata>);
    }
}

export class PlayRequest {
    "animeId": string;
    "episodeId": string;
    "startAt": number;

    /** Creates a new PlayRequest instance. */
    constructor($$source: Partial<PlayRequest> = {}) {
        if (!("animeId" in $$source)) {
            this["animeId"] = "";
        }
        if (!("episodeId" in $$source)) {
            this["episodeId"] = "";
        }
        if (!("startAt" in $$source)) {
            this["startAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayRequest($$parsedSource as Partial<PlayRequest>);
    }
}

export class ScheduleItem {
    "animeId": string;
    "episodeId": string;
    "airsAt": string;
    "precision": string;

    /** Creates a new ScheduleItem instance. */
    constructor($$source: Partial<ScheduleItem> = {}) {
        if (!("animeId" in $$source)) {
            this["animeId"] = "";
        }
        if (!("episodeId" in $$source)) {
            this["episodeId"] = "";
        }
        if (!("airsAt" in $$source)) {
            this["airsAt"] = "";
        }
        if (!("precision" in $$source)) {
            this["precision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ScheduleItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleItem($$parsedSource as Partial<ScheduleItem>);
    }
}

export class Settings {
    "appearance": string;
    "mpvPath": string;
    "autoplayNext": string;
    "resumePlayback": string;
    "language": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("appearance" in $$source)) {
            this["appearance"] = "";
        }
        if (!("mpvPath" in $$source)) {
            this["mpvPath"] = "";
        }
        if (!("autoplayNext" in $$source)) {
            this["autoplayNext"] = "";
        }
        if (!("resumePlayback" in $$source)) {
            this["resumePlayback"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = Anime.createFrom;
const $$createType1 = Metadata.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
