// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Catalog(): $CancellablePromise<$models.Anime[]> {
    return $Call.ByID(1063196325).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Detail(animeID: string): $CancellablePromise<$models.Detail> {
    return $Call.ByID(1357398543, animeID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Episodes(animeID: string): $CancellablePromise<$models.Episode[]> {
    return $Call.ByID(9390384, animeID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Follow(animeID: string): $CancellablePromise<void> {
    return $Call.ByID(1950924539, animeID);
}

export function Following(): $CancellablePromise<$models.Following[]> {
    return $Call.ByID(879874013).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetCover(animeID: string): $CancellablePromise<$models.Cover> {
    return $Call.ByID(1578927561, animeID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function History(): $CancellablePromise<$models.History[]> {
    return $Call.ByID(2534497190).then(($result: any) => {
        return $$createType9($result);
    });
}

export function Library(): $CancellablePromise<$models.Anime[]> {
    return $Call.ByID(4215164161).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Play(input: $models.PlayRequest): $CancellablePromise<void> {
    return $Call.ByID(3828312544, input);
}

export function RemoveHistory(animeID: string): $CancellablePromise<void> {
    return $Call.ByID(3491322938, animeID);
}

export function SaveSettings(input: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(640247734, input);
}

export function Schedule($from: string, to: string): $CancellablePromise<$models.ScheduleItem[]> {
    return $Call.ByID(3469096187, $from, to).then(($result: any) => {
        return $$createType11($result);
    });
}

export function Search(query: string): $CancellablePromise<$models.Anime[]> {
    return $Call.ByID(1479257982, query).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(874172507).then(($result: any) => {
        return $$createType12($result);
    });
}

export function Unfollow(animeID: string): $CancellablePromise<void> {
    return $Call.ByID(3872045128, animeID);
}

// Private type creation functions
const $$createType0 = $models.Anime.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Detail.createFrom;
const $$createType3 = $models.Episode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Following.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Cover.createFrom;
const $$createType8 = $models.History.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.ScheduleItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.Settings.createFrom;
